### ISSUE TITLE
Pack same data twice results in different checksums

### ISSUE THREAD

**Issue by n4uti** [zeroturnaround/zt-zip#107]
Why are there different checksums (md5) after packing the same content twice?

Thanks for help

**Comment by penn5** [comment]
Date modified?

**Comment by penn5** [comment]
Zip files by definition have a date modified/created field... I suppose it must be implemented in this library.

**Comment by penn5** [comment]
here you go: https://github.com/zeroturnaround/zt-zip/tree/master/src/main/java/org/zeroturnaround/zip/timestamps

**Comment by n4uti** [comment]
Thanks, i read about that windows zip or 7z each time packing the same data produces the same output and therefore the same md5. Donyou have any hints resolving this with the lib here. Thanks

**Comment by toomasr** [comment]
@n4uti  Can you provide a more complete sample? From the current ZipUtil.pack() usage that you posted I see that you are packing the bytes of "text".getBytes(). This should always produce the same md5. I wrote a quick example at https://gist.github.com/toomasr/9c37e5312b453e0a99d5c3fcf283719b

I presume you are dealing with the filesystem somehow and the timestamps do change as @penn5 pointed out. I'd like to figure out what exactly you are doing so that I know what exactly changes for you.

**Comment by n4uti** [comment]
Hello and thanks for your response.

I_m creating a file on the disk as folows:

`ZipEntrySource[] entries = new ZipEntrySource[1];
 entries[0] = new ByteSource(new File("meta.txt").getName(), "text".getBytes());
 ZipUtil.pack(entries, destFile);`

After the file was created i'm calculatikg the md5 as follows:

`//    MessageDigest md5Digest = MessageDigest.getInstance("MD5");
//    String checksum = getFileChecksum(md5Digest, destFile);

    public static String getFileChecksum(MessageDigest digest, File file) throws IOException {
        //Get file input stream for reading the file content
        FileInputStream fis = new FileInputStream(file);

        //Create byte array to read data in chunks
        byte[] byteArray = new byte[1024];
        int bytesCount = 0;

        //Read file data and update in message digest
        while ((bytesCount = fis.read(byteArray)) != -1) {
            digest.update(byteArray, 0, bytesCount);
        }

        //close the stream; We don't need it now.
        fis.close();

        //Get the hash's bytes
        byte[] bytes = digest.digest();

        //This bytes[] has bytes in decimal format;
        //Convert it to hexadecimal format
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < bytes.length; i++) {
            sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
        }

        //return finishWithError hash
        return sb.toString();
    }`

**Comment by toomasr** [comment]
I'm still not sure you are doing everything correctly as you are always compressing the bytes of the string "text" but nevertheless I think the issue is that the ByteSource constructor `public ByteSource(String path, byte[] bytes)` uses `System.currentTimeMillis()` for the timestamp.

If you use the constructor `public ByteSource(String path, byte[] bytes, long time)` then you can keep the time a constant.

**Comment by n4uti** [comment]
OK, yes i always want to pack the sring "text" in a zip archive with a file named "meta.txt". This is just for testing purposes to show, that the md5 sum always changes.

**Comment by n4uti** [comment]
Thanks for the hint with the constructor. I'll give it a try later when i'm at home.

**Comment by toomasr** [comment]
Feel free to re-open if problem persists.
