### ISSUE TITLE
Multi-thread

### ISSUE THREAD

**Issue by ShengjieGeng** [zeroturnaround/zt-zip#119]
hello! I want to unzip file by multi-thread.Could you please give me a favor?
thanks anyway.

**Comment by toomasr** [comment]
You would like to use multiple threads to unzip a single file? There isn't any multithreading support to unzip a single file.

**Comment by tiann** [comment]
Is there any way to zip a directory by multi-thread?

**Comment by toomasr** [comment]
Nothing built into the library. Since Java 8 there are nice features that you can take advantage of. See https://stackoverflow.com/questions/51920911/how-can-i-unzip-huge-folder-with-multithreading-with-java-preferred-java8

We should consider adding some of these to the zt-zip project also.

**Comment by tiann** [comment]
@toomasr In fact, multi-thread unzip has little improvements for performance, because it is the disk IO instead of cpu that influence the unzip.But the zip is mainly restricted by cpu because it is calculation-related.

There are lots of examples indicate that multi-thread zip can improve the performance heavily, such as pigz vs. gzip  pixz vs. xz
