### ISSUE TITLE
Add progress monitor support

### ISSUE THREAD

**Issue by reinra** [zeroturnaround/zt-zip#26]
Add a callback which gets events about the operation progress so users could update a progress bar e.g. Check other libraries for the same abstraction first.

**Comment by marcopenhacking** [comment]
I would be interested as well in that feature. Maybe you can retrieve it from the backlog.

**Comment by toomasr** [comment]
I tried to create a progress bar and this is how it turned out. See https://github.com/toomasr/zt-zip-progress-bar

It is a CLI progress bar. It generates 100 1mb files and then starts packing them. I'm using a NameMapper to hook into showing the progress bar on the console.

I'm using a file number approach. I have a 100 files and I show the percentage based on how many files have been processed. The other approach would be to do it based on how many bytes of the total bytes to be compressed have been processed.

I hope this helps.

**Comment by marcopenhacking** [comment]
Good starting point the nameMapper. Thanks a lot for the example!

**Comment by goxr3plus** [comment]
Great to have this feature in the library!!! :)

**Comment by AAChartModel** [comment]
Do you know that how to get Progress of Zipping and Unzipping the **single file** (not the ** folder**) ? 

Refer to the issue #116 

@reinra @shelajev @pommedeterresautee @marcopenhacking @goxr3plus Thanks🙂
